In [3]:
from scipy import linalg
import numpy as np

In [4]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

In [5]:
a

array([[ 3,  2,  0],
       [ 1, -1,  0],
       [ 0,  5,  1]])

In [6]:
b

array([ 2,  4, -1])

In [7]:
x = linalg.solve(a, b)

In [8]:
x

array([ 2., -2.,  9.])

In [9]:
np.dot(a, x) == b

array([ True,  True,  True])